title: Decaf and Mac
description: > # this means to ignore newlines until "baseurl:"
  Decaf and Mac's Blog<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://decafandmac.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'HanKi, Cho'
  last_name: 'Decaf and Mac'
  cv: ''
  avatar: '/images/avatar.jpeg'
  github_username: decafandmac
  email: eipeti.s2@gmail.com
  vk_id: ''
  telegram_name: ''
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


